<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>11</LangVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <OutputPath>bin/$(Configuration)/</OutputPath>
    <AssemblyName>MiniGameHotPotato</AssemblyName>
  </PropertyGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <MakeDir Directories="$(ProjectDir)mod\plugins" Condition="!Exists('$(ProjectDir)mod\plugins')" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ProjectDir)mod\plugins" />
    <Copy SourceFiles="$(TargetDir)$(TargetName).pdb" DestinationFolder="$(ProjectDir)mod\plugins"
      Condition="Exists('$(TargetDir)$(TargetName).pdb')" />
  </Target>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NUnit" Version="4.3.2" />
    <PackageReference Include="Lib.Harmony" Version="2.2.2" />
  </ItemGroup>


  <!--
    路径配置：
    设置环境变量 RW_PATH 指向 Rain World 安装目录即可跨平台使用。
  -->
  <PropertyGroup>
    <RWPath Condition="'$(RWPath)' == ''">/home/deck/.local/share/Steam/steamapps/common/Rain World/</RWPath>
  </PropertyGroup>

  <PropertyGroup>
    <WorkshopPath Condition="'$(WorkshopPath)' == ''">
      /home/deck/.local/share/Steam/steamapps/workshop/content/312520/</WorkshopPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="$(RWPath)/RainWorld_Data/Managed/*.dll" />
    <Reference Include="$(RWPath)/BepInEx/plugins/*.dll" />
    <Reference Include="$(RWPath)/BepInEx/core/*.dll" />

    <Reference Include="$(RWPath)/BepInEx/utils/*.dll"
      Condition="Exists('$(RWPath)/BepInEx/utils/')" />
  </ItemGroup>

  <!-- MOD 依赖 -->
  <ItemGroup>
    <Reference
      Include="$(WorkshopPath)/2933196558/newest/plugins/SlugBase.dll" />
    <Reference
      Include="$(WorkshopPath)/2920541687/newest/plugins/Fisobs.dll" />
    <Reference
      Include="$(WorkshopPath)/3388224007/plugins/*.dll" /><!-- Meadowmode -->
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="exemple\**" />
    <EmbeddedResource Remove="exemple\**" />
    <None Remove="exemple\**" />
  </ItemGroup>

</Project>